"""Pure game logic: content pools, hero model, combat (see docs/)."""

from apps.mini_rpg.core.choices import (attack_choice, defense_choice,
                                        levelup_choice,
                                        make_attack_validator,
                                        make_defense_validator,
                                        make_door_validator,
                                        make_levelup_validator,
                                        make_shop_validator)
from apps.mini_rpg.core.combat import (DIRECTIONS, LEVEL_SCALE, Combat,
                                       TurnResult, scale_mob)
from apps.mini_rpg.core.content import (DEFAULT_ITEMS_DIR, DEFAULT_MOBS_DIR,
                                        SLOTS, ContentError, Item, Mob,
                                        discover_items, discover_mobs,
                                        load_item, load_items, load_mob,
                                        load_mobs)
from apps.mini_rpg.core.hero import (CRIT_MULTIPLIER, CRIT_PER_LUCK,
                                     DAMAGE_STAT, HP_PER_ENDURANCE,
                                     MANA_PER_INTELLECT, STATS, WEAPON_SLOTS,
                                     XP_PER_LEVEL, Hero, new_hero)

__all__ = [
    "CRIT_MULTIPLIER",
    "CRIT_PER_LUCK",
    "DAMAGE_STAT",
    "DEFAULT_ITEMS_DIR",
    "DEFAULT_MOBS_DIR",
    "DIRECTIONS",
    "HP_PER_ENDURANCE",
    "LEVEL_SCALE",
    "MANA_PER_INTELLECT",
    "SLOTS",
    "STATS",
    "WEAPON_SLOTS",
    "XP_PER_LEVEL",
    "Combat",
    "ContentError",
    "Hero",
    "Item",
    "Mob",
    "TurnResult",
    "attack_choice",
    "defense_choice",
    "discover_items",
    "discover_mobs",
    "levelup_choice",
    "load_item",
    "load_items",
    "load_mob",
    "load_mobs",
    "make_attack_validator",
    "make_defense_validator",
    "make_door_validator",
    "make_levelup_validator",
    "make_shop_validator",
    "new_hero",
    "scale_mob",
]
