"""Pure game logic: content pools, hero model, combat (see docs/)."""

from apps.mini_rpg.core.choices import (door_commands, door_keys,
                                        levelup_choice, levelup_commands,
                                        levelup_keys, shop_commands,
                                        shop_keys)
from apps.mini_rpg.core.combat import (CHATTER_EMOJI, LEVEL_SCALE, ChatterUnit,
                                       Combat, CombatEvent, scale_mob)
from apps.mini_rpg.core.content import (DEFAULT_ITEMS_DIR, DEFAULT_MOBS_DIR,
                                        DEFAULT_PREFIXES, DEFAULT_PREFIXES_PATH,
                                        DEFAULT_STARTER, SLOTS, ContentError,
                                        Item, Mob, discover_items,
                                        discover_mobs, find_starters,
                                        load_item, load_items, load_mob,
                                        load_mobs, load_prefixes)
from apps.mini_rpg.core.hero import (CRIT_MULTIPLIER, CRIT_PER_LUCK,
                                     HP_PER_ENDURANCE,
                                     MANA_PER_INTELLECT, STATS, XP_PER_LEVEL,
                                     Hero, new_hero)

__all__ = [
    "CHATTER_EMOJI",
    "CRIT_MULTIPLIER",
    "CRIT_PER_LUCK",
    "ChatterUnit",
    "CombatEvent",
    "DEFAULT_ITEMS_DIR",
    "DEFAULT_MOBS_DIR",
    "DEFAULT_PREFIXES",
    "DEFAULT_PREFIXES_PATH",
    "DEFAULT_STARTER",
    "HP_PER_ENDURANCE",
    "LEVEL_SCALE",
    "MANA_PER_INTELLECT",
    "SLOTS",
    "STATS",
    "XP_PER_LEVEL",
    "Combat",
    "ContentError",
    "Hero",
    "Item",
    "Mob",
    "discover_items",
    "discover_mobs",
    "door_commands",
    "door_keys",
    "find_starters",
    "levelup_choice",
    "levelup_commands",
    "levelup_keys",
    "load_item",
    "load_items",
    "load_mob",
    "load_mobs",
    "load_prefixes",
    "new_hero",
    "scale_mob",
    "shop_commands",
    "shop_keys",
]
