"""Pure game logic: content pools, hero model, combat (see docs/)."""

from apps.mini_rpg.core.choices import (attack_choice, attack_commands,
                                        attack_keys, defense_choice,
                                        defense_commands, defense_keys,
                                        door_commands, door_keys,
                                        levelup_choice, levelup_commands,
                                        levelup_keys, shop_commands,
                                        shop_keys)
from apps.mini_rpg.core.combat import (DIRECTIONS, LEVEL_SCALE, Combat,
                                       TurnResult, scale_mob)
from apps.mini_rpg.core.content import (DEFAULT_ITEMS_DIR, DEFAULT_MOBS_DIR,
                                        DEFAULT_PREFIXES, DEFAULT_PREFIXES_PATH,
                                        SLOTS, ContentError, Item, Mob,
                                        discover_items, discover_mobs,
                                        load_item, load_items, load_mob,
                                        load_mobs, load_prefixes)
from apps.mini_rpg.core.hero import (CRIT_MULTIPLIER, CRIT_PER_LUCK,
                                     DAMAGE_STAT, HP_PER_ENDURANCE,
                                     MANA_PER_INTELLECT, STATS, WEAPON_SLOTS,
                                     XP_PER_LEVEL, Hero, new_hero)

__all__ = [
    "CRIT_MULTIPLIER",
    "CRIT_PER_LUCK",
    "DAMAGE_STAT",
    "DEFAULT_ITEMS_DIR",
    "DEFAULT_MOBS_DIR",
    "DEFAULT_PREFIXES",
    "DEFAULT_PREFIXES_PATH",
    "DIRECTIONS",
    "HP_PER_ENDURANCE",
    "LEVEL_SCALE",
    "MANA_PER_INTELLECT",
    "SLOTS",
    "STATS",
    "WEAPON_SLOTS",
    "XP_PER_LEVEL",
    "Combat",
    "ContentError",
    "Hero",
    "Item",
    "Mob",
    "TurnResult",
    "attack_choice",
    "attack_commands",
    "attack_keys",
    "defense_choice",
    "defense_commands",
    "defense_keys",
    "discover_items",
    "discover_mobs",
    "door_commands",
    "door_keys",
    "levelup_choice",
    "levelup_commands",
    "levelup_keys",
    "load_item",
    "load_items",
    "load_mob",
    "load_mobs",
    "load_prefixes",
    "new_hero",
    "scale_mob",
    "shop_commands",
    "shop_keys",
]
